### PR TITLE
First draft of full docs

### PR DESCRIPTION
**Pull request by CamSoper**
First draft of the full set of documentation is [staged on my personal GitHub site](https://camsoper.github.io/nerdstack.github.io/)!  Feedback welcome.  Comment here or send me a PR, please.

**CC:**
@tstringer
@jplane
@tripdubroot
@kottofy
@aliuy
@mahaase1

### CODE REVIEW

**Comment by trstringer** [comment]
Wow, that looks really good 😮 👍 

Looks good to me, although I'll wait for other team members' input as well.

Thank you for doing this!

**Comment by jplane** [comment]
Agree... this looks great @CamSoper... thanks a ton! The walkthru is excellent too... great screenshots, etc. Very clean, simple, and useful.

**Comment by aliuy** [comment]
I love it!!

**Comment by CamSoper** [comment]
Hey, @tripdubroot , Folks seem pretty pleased.  If you're good with them, go ahead and merge the PR.  :)

**Pull request merged**
